modLoader = "javafml"
loaderVersion = "[37,)"
#loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/Richy-Z/ThreatenGL/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "threatengl"
version = "${version}"
displayName = "ThreatenGL"
authors = "Richy Z."
description = "Threatens Minecraft to use a different version of OpenGL."
logoFile = "threatengl-icon-notext-128.png"
displayURL = "https://modrinth.com/mod/threatengl"

[[dependencies.threatengl]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.threatengl]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "CLIENT"
