modLoader = "javafml"
# Forge 1.17.1 and up
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/Numelon-Softworks/ThreatenGL/issues"
license = "Unknown"

[[mods]]
modId = "threatengl"
version = "${version}"
displayName = "ThreatenGL"
authors = "Richy Z, Numelon"
description = '''
Threatens Minecraft to use a different version of OpenGL.
'''
logoFile = "assets/threatengl/threatengl-icon-notext-128.png"
modUrl = "https://modrinth.com/mod/threatengl"
displayURL = "https://modrinth.com/mod/threatengl"

[[dependencies.threatengl]]
modId = "forge"
mandatory = true
# Forge 1.17.1 and up (fml 37)
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.threatengl]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.threatengl]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
