modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Numelon-Softworks/ThreatenGL/issues"
license = "Unknown"

[[mods]]
modId = "threatengl"
version = "${version}"
displayName = "ThreatenGL"
authors = "Richy Z, Numelon"
description = '''
Threatens Minecraft to use a different version of OpenGL.
'''
logoFile = "threatengl-icon-notext-128.png"
modUrl = "https://modrinth.com/mod/threatengl"
displayURL = "https://modrinth.com/mod/threatengl"

[[dependencies.threatengl]]
modId = "neoforge"
type = "required"
# 1.20.1 has the old Forge Mod Loader versioning system
# 1.20.1 has 40* version naming, whereas 1.20.2 has 20.2.* and 1.20.3 has 20.3.* etc
# Therefore we have to specify [20,) instead of [40,) otherwise that will invalidate future Minecraft releases and future NeoForge loader releases who have the new versioning system instead of the fml versioning system
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.threatengl]]
modId = "minecraft"
type = "required"
# Note that NeoForged was created in July 2023 and thus does not have support before Minecraft 1.20.1
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.threatengl]]
modId = "architectury"
type = "optional"
# NeoForge specific versions of architectury arent available for 1.20.1
# however Forge specific versions are, and this is the last version supporting 1.20.1
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "threatengl.mixins.json"
