modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Richy-Z/ThreatenGL/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "threatengl"
version = "${version}"
displayName = "ThreatenGL"
authors = "Richy Z."
description = "Threatens Minecraft to use a different version of OpenGL."
logoFile = "threatengl-icon-notext-128.png"
displayURL = "https://modrinth.com/mod/threatengl"

[[dependencies.threatengl]]
modId = "neoforge"
# type = "required"
mandatory = true
# 1.20.1 has the old forge mod loader versioning system
# unfortunately we will be dropping 1.20.1 support
# who uses that version anyway?
versionRange = "[20.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.threatengl]]
modId = "minecraft"
# type = "required"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "threatengl.mixins.json"