name: 🔨 Build ThreatenGL
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        java: [21]

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build ThreatenGL
        run: ./gradlew build

      - name: Bundle mod loader jars for upload
        run: |
          mkdir gh-artefacts-upload
          mv fabric/build/libs/*.jar gh-artefacts-upload/
          mv forge/build/libs/*.jar gh-artefacts-upload/
          mv neoforge/build/libs/*.jar gh-artefacts-upload/
          mv quilt/build/libs/*.jar gh-artefacts-upload/

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: Built Artefacts
          path: gh-artefacts-upload/
